title: "Chrysanthemum's ePortfolio"
author: "C. Gribble Gilbert"
description: "Capstone ePortfolio showcasing Software Engineering, Algorithms & Data Structures, and Database design."
theme: jekyll-theme-hacker
show_downloads: false
